language: generic

sudo: required
services:
  - docker


before_install:
  - docker build -t everestyeti/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true everestyeti/docker-react npm run test -- --coverage